theme: minima # 官方默认主题
# theme: jekyll-theme-hacker  # GitHub 官方提供的黑客风格主题

# remote_theme: pages-themes/merlot@v0.2.0

title: MWWZTECH

collections:
  posts:
    output: true
    # permalink: /:year/:month/:day/:title.html


# 构建配置
markdown: kramdown
kramdown:
  # math_engine: katex
  math_engine: mathjax  # 使用MathJax作为数学引擎
  syntax_highlighter: rouge  # 代码高亮
  
highlighter: rouge
permalink: /:year/:month/:day/:title/  # 文章永久链接格式
plugins:
  - jekyll-feed       # 生成 RSS 订阅
  - jekyll-seo-tag    # 增强 SEO
  - jekyll-sitemap    # 生成站点地图
  - jekyll-remote-theme # add this line to the plugins list if you already have one